### ISSUE TITLE
Surface Abstraction needs refinement

### ISSUE THREAD

**Issue by cfgoldsmith** [cfgoldsmith/RMG-Py#10]
Currently, we allow the surface abstraction family to pass any functional group from one adsorbate to another. Presently, this family accounts for the majority of all reactions in the core. As a consequence, we really need to refine the rate parameters so that we provide a different set of A,Ea if we pass H vs OH vs CH3, etc.

**Comment by rwest** [comment]
For this family:
```
 *1   *4-*3             *1-*4  *3
 ||       |      ---->   |     ||
~*2~~ + ~*5~~          ~*2~ + ~*5~~
```

One has to decide how to structure the tree, which needs a combination of intuition of what matters most chemically, and some respect of what's feasible/straightforward to define functional groups for.

Eg. Perhaps most important thing (hence what should be first division point in your tree) is whether you're passing an atom (H), versus 2 atoms (OH), versus 4 atoms (CH3), versus 7 atoms (CH2CH3).
Or perhaps it's most important whether you're breaking a CH bond (passing H), versus a CO bond (passing OH), versus a CC bond (CH3 and CH2CH3).

The latter case is easier to write functional group definitions for (you say atom *4 is either an H an O or a C - easy!) so would be the obvious choice for most RMG developers.

Maybe the bond you're making (identity of atom *1) is also important.

Then you must expand the tree with your group names, and define each of them in the `groups.py` file.

Then if you have general rate rules, you may specify them in rules.py.
If you have specific reactions, we prefer to put them in a `training` folder, which looks like a reaction library but with labeled atoms. These `training reactions` will get placed in the correct place in the tree at load time, then averaged up to fill empty nodes (though won't alter any nodes defined in rules.py).

I have just pushed 09c0a1994ae15c0dbb3e1be9b1221f146893e9af which demonstrates the approach.

**Comment by cfgoldsmith** [comment]
OK, excellent. I'm giving that a shot now.
