### ISSUE TITLE
solver simulation.csv is a mess

### ISSUE THREAD

**Issue by cfgoldsmith** [cfgoldsmith/RMG-Py#15]
When outputting the simulation results into the solver/simulation_1_#.csv, RMG-Cat converts _everything_ to mole fractions for a single phase. It would be much better to recognize that we have two phases -- a gas phase and a gas/surface interace -- and each one should have its own respective dimensionless concentration.

**Comment by rwest** [comment]
See #9. Simulation csv now outputs numbers of moles of things.
