### ISSUE TITLE
RMG-Cat cannot recognize quadruple bonds

### ISSUE THREAD

**Issue by cfgoldsmith** [cfgoldsmith/RMG-Py#2]
In the gas phase, we typically do not think of CC as having a "quadruple bond" but rather a triple bond and two unpaired electrons. For a carbon adatom, in contrast, we want to avoid the unpaired electron, so we need to create a quadruple bond (i.e. all for valence electrons are bonded to the surface).

**Comment by rwest** [comment]
Quadruple bonds now exist but...

- [ ] drawing of them is incorrect
- [ ] `X~C` must exist in the thermo library

**Comment by rwest** [comment]
Checked the thermo exists (it does) and fixed the drawing in ad1bf6cae5528468cc39fd78feb31bef25e30be9. It seems I'm unable to close issues on your issue tracker though.

**Comment by cfgoldsmith** [comment]
Excellent.
