### ISSUE TITLE
ck2cti conversion fails on our chemkin file. Suspects unmarked duplicate reaction

### ISSUE THREAD

**Issue by rwest** [cfgoldsmith/RMG-Py#29]
At end of model generation, the conversion to cantera fails with 
```
Warning: 
ERROR: Unable to parse '/Users/rwest/Code/Cat/RMG-Py/testing/surface/chemkin/chem.inp' near line 635:

Error: Could not generate Cantera files for some reason.
Traceback (most recent call last):
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/main.py", line 787, in execute
    self.generateCanteraFiles(os.path.join(self.outputDirectory, 'chemkin', 'chem.inp'))
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/main.py", line 1049, in generateCanteraFiles
    parser.convertMech(chemkinFile, outName=outName, quiet=True, permissive=True, **kwargs)
  File "/Users/rwest/anaconda/envs/rmgcat3/lib/python2.7/site-packages/cantera/ck2cti.py", line 2172, in convertMech
    self.loadChemkinFile(inputFile)
  File "/Users/rwest/anaconda/envs/rmgcat3/lib/python2.7/site-packages/cantera/ck2cti.py", line 1886, in loadChemkinFile
    self.checkDuplicateReactions()
  File "/Users/rwest/anaconda/envs/rmgcat3/lib/python2.7/site-packages/cantera/ck2cti.py", line 1925, in checkDuplicateReactions
    raise InputParseError(message.format(r1, r1.line_number, r2.line_number))
InputParseError: Encountered unmarked duplicate reaction CH3X(22) + HOX(23) <=> CH4(1) + site(18) + OX(20) (See lines 420 and 420 of the input file.).

```
Notice that the duplicates are both on line 420!??

As far as I can tell (cursory search), the reaction isn't duplicated.

Here's the chemkin file.
[chem.txt](https://github.com/cfgoldsmith/RMG-Py/files/1962812/chem.txt)

 It may be a cantera ck2cti bug.
Or maybe our chemkin file is invalid for some other reason.
Possibly relevant: the *previous* reaction was a STICK kind.

**Comment by rwest** [comment]
Our chemkin file(s) were invalid *and* we were calling ck2cti incorrectly.

Some example chemkin files can be found at 
https://github.com/Cantera/cantera/blob/master/test/data/surface1.inp and 
https://github.com/Cantera/cantera/blob/master/test/data/surface1-gas.inp
and for reference, the cantera issue where Ray helpfully points out our errors is at 
https://github.com/Cantera/cantera/issues/532

**Comment by mazeau** [comment]
- [x] get the chemkin-writing parts of RMG to know when they're dealing with a surface model
- [x] make two files, one for surface one for gas.
- [x] get RMG to delete, rename, etc both these files while building the model
- [x] put the surface species and their thermo into the surface file
- [x] put all reactions with the surface into the surface file
- [x] add `X /195.083/`  (that's the molecular weight of platinum) to the element list (in the gas file)
- [ ] at the top of the surface file put something like
```
SITE/PT_SURFACE/    SDEN/2.72E-9/
_Pt_ H_Pt O2_Pt/3/ H2O_Pt OH_Pt O_Pt
END
```
   where `PT_SURFACE` is replaced our name for the vacant site (eg. `site(18)`) and `2.72E-9` is our surface site density (what units??), and what follows is a list of the surface species names. The `/3/` in the example is for a species that uses 3 sites. 
- [ ] fix the ck2cti conversion to cantera that happens at the end of the job
- [ ] options for the future: `FORD` `COV` `MWON` `MWOFF`

**Comment by mazeau** [comment]
Inside RMG-Cat, the surface site density can be different for every reactor simulation (set by `surfaceSiteDensity=(2.9e-9, 'mol/cm^2'),`), and is not part of the reaction model. So we can't put them in the chemkin file (the `SDEN/2.72E-9/` line) because we may have more than one. Does that make it invalid? should we pick one? any ideas @cfgoldsmith ?

**Comment by cfgoldsmith** [comment]
Hmm. In reality, it should be a user-defined option at the input file level, but it should not change within an input file; the temperature, pressure, and composition should change, but not the surface site density. It could/should change from one surface to the next (e.g. different metals, or different facets of the same metal). My thinking is that we just write the first one to the cti file and trust that the user isn't doing something daft. Open to counter suggestions, though.

**Comment by cfgoldsmith** [comment]
I presume that the units of SDEN are consistent with the units declaration (e.g. mol/cm^2).

**Comment by rwest** [comment]
I think everything here was resolved in https://github.com/ReactionMechanismGenerator/RMG-Py/commit/7aafbd9910c9e9fce4bdac014433e884f3294958
