### ISSUE TITLE
Error when including gas-phase reaction libraries

### ISSUE THREAD

**Issue by kblondal** [cfgoldsmith/RMG-Py#54]
When trying to include gas-phase reaction libraries ('BurkeH2O2inN2' and 'ERC-FoundationFuelv0.9'), either as seed mechanisms or reaction libraries in my RMG-Cat input file, I get the error message:
File "rmgpy/chemkin.pyx", line 1691, in rmgpy.chemkin.writeKineticsEntry
arrhenius.A.value_si / (arrhenius.T0.value_si ** arrhenius.n.value_si) * kinetics.A.getConversionFactorFromSItoCM(),
AttributeError: 'rmgpy.kinetics.falloff.Troe' object has no attribute 'A'

**Comment by cfgoldsmith** [comment]
I want to update this issue. It seems that some of the reaction libraries in RMG are no longer compatible. However, BurkeH2O2 and CombustionCore do seem to work with the latest stable master. More to the point, we can use the _RMG-Cat_ executable to run an input.py that includes these two reaction libraries, if we use a constant-TP batch reactor with no catalyst, but when we switch to a constant-TV batch with a catalyst, we cannot use the reaction libraries. RMG-Cat throws up an error regarding non-constant pressure. Katrin will post the error message.

**Comment by kblondal** [comment]
Yes, this is where the run stops:

--------------------------------------
Created 1 new edge species
    C.\[Ni](50)
Added 0 new core reactions
Created 3 new edge reactions
    H2(4) + CH2(S)(29) <=> CH4(2)
    CH4(2) + X(1) <=> C.\[Ni](50)
    CH4(2) + O2(3) <=> HO2(23) + CH3(32)

After model enlargement:
    The model core has 5 species and 0 reactions
    The model edge has 47 species and 160 reactions


Completed initial enlarge edge step.

Saving current model core to Chemkin file...
Chemkin file contains 0 reactions.
Chemkin file contains 0 reactions.
Saving annotated version of Chemkin files...
Chemkin file contains 0 reactions.
Chemkin file contains 0 reactions.
Saving current model core to HTML file...
Updating RMG execution statistics...
    Execution time (DD:HH:MM:SS): 00:00:02:04
    Memory used: 610.27 MB

Beginning model generation stage 1...

Conducting simulation of reaction system 1...
Error: Model core reactions:
Error: []
Making seed mechanism...
Traceback (most recent call last):
  File "rmg.py", line 173, in <module>
    main()
  File "rmg.py", line 167, in main
    rmg.execute(**kwargs)
  File "/home/kblondal/RMG-pyGitHub/RMG-Py/rmgpy/rmg/main.py", line 741, in execute
    conditions = self.rmg_memories[index].get_cond()
  File "rmgpy/solver/base.pyx", line 564, in rmgpy.solver.base.ReactionSystem.simulate
    cpdef simulate(self, list coreSpecies, list coreReactions, list edgeSpecies,
  File "rmgpy/solver/base.pyx", line 663, in rmgpy.solver.base.ReactionSystem.simulate
    self.initializeModel(coreSpecies, coreReactions, edgeSpecies, edgeReactions, surfaceSpecies, surfaceReactions, 
  File "rmgpy/solver/surface.pyx", line 183, in rmgpy.solver.surface.SurfaceReactor.initializeModel
    self.generate_rate_coefficients(coreReactions, edgeReactions)
  File "rmgpy/solver/surface.pyx", line 209, in rmgpy.solver.surface.SurfaceReactor.generate_rate_coefficients
    assert not rxn.kinetics.isPressureDependent(), "Pressure may be varying."
AssertionError: Pressure may be varying.

**Comment by kblondal** [comment]
A link to the input file I was using:
[https://github.com/kblondal/RMG-Py/blob/cat_testing/cat_inputfiles/catalysis_included_190115/input.py](url)

**Comment by rwest** [comment]
Thanks for the input file.

The trouble is in `generate_rate_coefficients(self, coreReactions, edgeReactions)`
https://github.com/rwest/RMG-Py/blob/cat/rmgpy/solver/surface.pyx#L192
we pre-calculate a bunch of k values, which are assumed to stay constant during the ODE solve, so the ode solver just multiplies them by the species concentrations (with relevant stoichiometry powers) to get the rates of progress.

We have never had to re-calculate the k values during each call to the right hand side of the ODE equation before, because we always had isothermal, isobaric, conditions.

We could temporarily remove the assertion check so that it doesn't crash, but it'll evaluate those pressure-dependent kinetics using the initial pressure, not the actual current pressure.

**Comment by rwest** [comment]
I just pushed a commit that addresses this by essentially warning and carrying on with an incorrect simulation.
 I think this now runs into the bug at the top of this thread (AttributeError: 'rmgpy.kinetics.falloff.Troe' object has no attribute 'A') ?

**Comment by cfgoldsmith** [comment]
Right. Thank you. My suggestion is that we remove the assertion check for the time being. I suppose it is possible that the pressure could change a lot, but I suspect that for most simulations, it is unlikely to change so much that the pdep kinetics would be wildly different. (if we did catalytic combustion or partial oxidation and did not include a bath gas, you'd have to have a pretty large fuel to generate an order of magnitude increase in pressure, right?).
[edit: I was typing this while you made your second post]

**Comment by kblondal** [comment]
Thank you. And yes, after pulling your changes, recompiling and running rmg-cat with the same input file, it throws up the error at the top of this thread.

**Comment by kblondal** [comment]
I also get the error reported at the top of this thread if I use a constant T, P reactor without catalysis for methane oxidation, as in the following input file:
https://github.com/kblondal/RMG-Py/blob/cat_testing/cat_inputfiles/no_catalysis_190115/input.py

I don't get the error if don't include any reaction libraries in the input file.

**Comment by rwest** [comment]
I just pushed another change (to my cat branch) which I think should fix this.

If possible, please check that any Troe rate expressions in the input library get written out correctly in the chemkin file and there are no weird units errors (powers of ten changes in the A number).

**Comment by kblondal** [comment]
Great, thanks! Will do.
