### ISSUE TITLE
When RMG-Cat crashes, print reaction family that caused it

### ISSUE THREAD

**Issue by cfgoldsmith** [cfgoldsmith/RMG-Py#6]
Currently, when RMG-Cat crashes, we print the reactants and products that caused the error. This is helpful. It would be more helpful to include the reaction family that caused the crash. For example, right now I get an error:
Error: Reactant: Molecule(SMILES="O=[C]O[Ni]")
Error: Reactant: Molecule(SMILES="[Ni]")
Error: Product: Molecule(SMILES="O=C([Ni])O[Ni]")
I think maybe it is caused by Surface_Adsorption_Single, because I think it is (maybe?!?) trying to desorb one half of a di-sigma bonded species, but I really don't know.

**Comment by rwest** [comment]
Good idea. Where best to add this depends a bit on where it crashed. If you have (or can reproduce) the full stack trace of the crash that would help put the extra debugging info in the right place.

**Comment by rwest** [comment]
Issue #7 reports more of the error message

>Error: Reactant: Molecule(SMILES="O=[C]O[Ni]")
Error: Reactant: Molecule(SMILES="[Ni]")
Error: Product: Molecule(SMILES="O=C([Ni])O[Ni]")
rmgpy.data.kinetics.common.KineticsError: Unable to calculate degeneracy for reaction + <=> in reaction family Surface_Adsorption_Single. Expected 1 reaction but generated 0

which says _in reaction family Surface_Adsorption_Single._

So in this case it seems we already print the reaction family.
If you have another crash that doesn't report the family, reopen the issue with the full stack trace :)

**Comment by cfgoldsmith** [comment]
Ah, yes. So it does! I'll see if I can get it to reproduce the earlier error...
