### ISSUE TITLE
Can't scale to N?

### ISSUE THREAD

**Issue by mazeau** [cfgoldsmith/RMG-Py#66]
the last commit on my cat and richard's cat adds N in the linear scaling, even though we don't scale to N.  Adding back the N into line 1287 in thermo.py gives this error:
```
deltaAtomicAdosrptionEnergy[element].value_si =  bindingEnergies[element].value_si - deltaAtomicAdosrptionEnergy[element].value_si
KeyError: 'N'
```
so I have removed it.

**Comment by mazeau** [comment]
maybe finished...?  https://github.com/mazeau/RMG-Py/commit/f6354b0ac429c74d6ac2fe4fec1668608fc17425 have not tested it yet

no more errors anymore when running a normal input file with only scaling to c and o so N should probably work

**Comment by rwest** [comment]
Cherry-picked to catmerge and electron count fixed. Thanks
