### ISSUE TITLE
Surface site density always 2.9e-09 mol/cm^2 in Chemkin and Cantera files

### ISSUE THREAD

**Issue by kblondal** [cfgoldsmith/RMG-Py#68]
The Chemkin and Cantera files generated by RMG-Cat have the site density used for nickel, 2.9e-09, also when running for processes on platinum. For example in Cantera, in the ideal_interface entry at the top, site_density=2.9e-09 even though I set it to 2.72e-9 for platinum in the RMG-Cat input file reactors.

Since this is a part of the input for the surface reactors (surfaceSiteDensity=(2.72e-9, 'mol/cm^2')), perhaps that should be used to make Chemkin and Cantera print the appropriate values for the surface in question?

**Comment by rwest** [comment]
Sounds like a pretty clearly defined bug/improvement. Would you like to try and fix it? Probably in the CHEMKIN writer (the Cantera files are just made from those).

**Comment by kblondal** [comment]
So far I learned that the surface site density should be stored in the RMG class attribute 'reactionSystems', but I do not know how to take it from there and put it in the chemkin and cantera files, although I believe that is where I should take it from. 

My current approach is just putting a "read input file" function in the chemkin.pyx file and find the surface site density that way. I get the desired result but I know it is inefficient and I would like to be able to use what I believe is already stored in the RMG class attribute. How would I import that into the chemkin.pyx file?

Current solution:
https://github.com/kblondal/RMG-Py/blob/cat-sitedensity/rmgpy/chemkin.pyx
(added function starting in line 1367 and lines 2022-2024)

**Comment by rwest** [comment]
Now fixed! You can specify in the input file, and it ends up in the output file.
