### ISSUE TITLE
RMG-Cat has two phases, but Solver/simulation_*.csv converts everything to a single array of mole fractions

### ISSUE THREAD

**Issue by cfgoldsmith** [cfgoldsmith/RMG-Py#9]
RMG-Cat uses moles for the governing equations, and the solver folder has mole fractions. The solver folder is great for plotting. However, it converts everything to a single array of mole fractions, even though technically we have two phases. In other words, if I start off with y_ch4 = 0.5, y_o2 = 0.5, and theta_\* = 1.0, solver/simulation_.csv returns:
y_ch4 = 0.3
y_o2 = 0.3
y_site = 0.4
[Note: the 0.3, 0.3, and 0.4 come from the surface-area-to-volume ratio, and the surface site density, when you do all the math...]
I can separate the gas and surface phases and renormalize manually, but that is a pain.

**Comment by rwest** [comment]
simulation_.csv now reports numbers of moles of things, not normalized to anything (except at the START you have 1 mole of gas phase).
